### ISSUE TITLE
Broken Actions

### ISSUE THREAD

**Issue by biellls** [typhoon-data-org/typhoon-orchestrator#7]
The docker image build fails with the following error:

```
------
 > [4/5] RUN cd /opt/ && typhoon init typhoon_project:
#9 2.514     dag_schema, component_schema = generate_json_schemas()
#9 2.514   File "/typhoon/cli_helpers/json_schema.py", line 109, in generate_json_schemas
#9 2.514     for function_info in local_functions_info():
#9 2.514   File "/typhoon/introspection/introspect_local_project.py", line 14, in local_functions_info
#9 2.514     spec.loader.exec_module(functions_module)
#9 2.514   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
#9 2.514   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
#9 2.514   File "/opt/typhoon_project/functions/open_library_api.py", line 43, in <module>
#9 2.514     from fuzzywuzzy import fuzz
#9 2.514 ModuleNotFoundError: No module named 'fuzzywuzzy'
------
error: failed to solve: executor failed running [/bin/sh -c cd /opt/ && typhoon init $PROJECT_NAME]: exit code: 1
Error: buildx call failed with: error: failed to solve: executor failed running [/bin/sh -c cd /opt/ && typhoon init $PROJECT_NAME]: exit code: 1
```

## How to fix
We have several options:

1. Add it to the project requirements
2. Add it to a separate requirements in the example directory and do `pip install -r requirements.txt` in the Dockerfile or entrypoint for the generated requirements after `typhoon init`.
3. Separate the example repos

I favor option 2. because we want to keep the project requirements minimal and separating the examples is much more work and won't immediately solve the issue without also installing the requirements from the external repo similar to option 2.

**Comment by biellls** [comment]
We can take advantage of this to automatically install the extra requirements. https://github.com/puckel/docker-airflow#install-custom-python-package

**Comment by grimfandangle** [comment]
Temporary removed it for now - but will fix this so we can add back in.

**Comment by grimfandangle** [comment]
closed.
